---
name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:
    inputs:
      use_cache:
        description: "Use build cache"
        required: true
        type: boolean
        default: true

jobs:
  build:
    name: Build multi-arch image
    uses: docker/github-builder/.github/workflows/build.yml@v1
    with:
      output: image
      platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x
      push: ${{ github.event_name != 'pull_request' }}
      cache: ${{ github.event.inputs.use_cache || 'true' }}
      sign: auto
      sbom: true
      meta-images: ${{ github.repository }}
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
      set-meta-annotations: true
      set-meta-labels: true
      labels: |
        org.opencontainers.image.title=Oktomusic Custom FFmpeg
        org.opencontainers.image.description=Custom build of FFmpeg for Oktomusic project
        org.opencontainers.image.authors=AFCMS <afcm.contact@gmail.com>
        org.opencontainers.image.licenses=LGPL-2.1-only
        org.opencontainers.image.source=https://github.com/oktomusic/ffmpeg-custom
        io.artifacthub.package.readme-url=https://raw.githubusercontent.com/oktomusic/ffmpeg-custom/refs/heads/master/README.md
        io.artifacthub.package.category=skip-prediction
        io.artifacthub.package.keywords=music,media,tool
        io.artifacthub.package.license=LGPL-2.1-only
        io.artifacthub.package.maintainers=[{"name":"AFCMS","email":"afcm.contact@gmail.com"}]
      annotations: |
        org.opencontainers.image.title=Oktomusic Custom FFmpeg
        org.opencontainers.image.description=Custom build of FFmpeg for Oktomusic project
        org.opencontainers.image.authors=AFCMS <afcm.contact@gmail.com>
        org.opencontainers.image.licenses=LGPL-2.1-only
        org.opencontainers.image.source=https://github.com/oktomusic/ffmpeg-custom
        io.artifacthub.package.readme-url=https://raw.githubusercontent.com/oktomusic/ffmpeg-custom/refs/heads/master/README.md
        io.artifacthub.package.category=skip-prediction
        io.artifacthub.package.keywords=music,media,tool
        io.artifacthub.package.license=LGPL-2.1-only
        io.artifacthub.package.maintainers=[{"name":"AFCMS","email":"afcm.contact@gmail.com"}]

    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
